let ideas = {
    ideas: [
        'a House',
        'a Tree',
        'a Car',
        "Hearts",
        "Flowers",
        "Fruit",
        "Stars",
        "Eyes",
        "Lips",
        "Trees",
        "Butterflies",
        "Leaves",
        "Diamonds",
        "Small Animals",
        "Cartoon Characters",
        "Rain Clouds",
        "Sunshine",
        "Teddy Bears",
        "Tricycles",
        "Candy Canes",
        "Snowmen",
        "Rainbows",
        "Your Pet",
        "Anime",
        "Dragons",
        "Music",
        "Spaceships",
        "Waves",
        "Architectural Designs",
        "Spiderwebs",
        "Ninjas",
        "Electronic Circuits",
        "Musical Instruments",
        "Cityscapes",
        "Facial Expressions",
        "Hand Gestures",
        "Vehicles",
        "3D Forms",
        "Ghosts",
        "Footprints in the Sand",
        "Snakes",
        "Aliens",
        "Van Gogh’s Starry Night"
    ]
};

module.exports = ideas;